language: python
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8
    - nightly
    - pypy3

install: pip install flake8 pytest pytest-cov .
before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script: py.test -v --cov=surt
