# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.5-dev
    - nightly
    - pypy
    - pypy3

install: pip install . pytest pytest-cov
script: py.test -v --cov=surt tests/

